# Generated by Django 2.2.5 on 2020-01-21 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='number_view',
            field=models.IntegerField(default=0, verbose_name='公告被收藏数'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='update_time',
            field=models.DateTimeField(verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='noticemessage',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未回复'), (1, '已回复')], default=0, verbose_name='留言状态'),
        ),
        migrations.CreateModel(
            name='NoticeReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('leave_message', models.CharField(max_length=256, verbose_name='留言回复')),
                ('goods_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.NoticeMessage', verbose_name='公告留言')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '公告留言回复',
                'verbose_name_plural': '公告留言回复',
                'db_table': 'st_notice_reply',
            },
        ),
    ]
