# Generated by Django 2.2.5 on 2020-01-22 04:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20200121_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='公告详情'),
        ),
    ]
