# Generated by Django 2.2.5 on 2020-01-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20200122_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticereply',
            old_name='goods_mes',
            new_name='notice_mes',
        ),
        migrations.RemoveField(
            model_name='noticemessage',
            name='reply',
        ),
        migrations.AlterField(
            model_name='notice',
            name='number_view',
            field=models.IntegerField(default=0, verbose_name='公告浏览数'),
        ),
    ]
