# Generated by Django 2.2.5 on 2020-01-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191221_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_portrait',
            field=models.ImageField(default='group1/M00/00/00/wKj4gV4jxYSAIpfuAAADj51SOaA880.png', upload_to='head', verbose_name='头像路径'),
        ),
    ]
