# Generated by Django 2.2.5 on 2020-01-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200119_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_portrait',
            field=models.ImageField(default='group1/M00/00/00/rB4AC14zm7OAAyEZAAADj51SOaA057.png', upload_to='head', verbose_name='头像路径'),
        ),
    ]
