# Generated by Django 2.2.5 on 2020-01-19 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0004_auto_20200119_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsleavemessage',
            name='reply',
        ),
        migrations.AlterField(
            model_name='goods',
            name='fineness',
            field=models.SmallIntegerField(choices=[(3, '7成新及以下'), (1, '9成新'), (2, '8成新'), (0, '全新')], default=0, verbose_name='商品成色'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('leave_message', models.CharField(max_length=256, verbose_name='留言回复')),
                ('goods_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsLeaveMessage', verbose_name='留言')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '留言回复',
                'verbose_name_plural': '留言回复',
                'db_table': 'st_reply',
            },
        ),
    ]
