# Generated by Django 2.2.5 on 2020-01-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20200120_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='fineness',
            field=models.SmallIntegerField(choices=[(0, '全新'), (3, '7成新及以下'), (2, '8成新'), (1, '9成新')], default=0, verbose_name='商品成色'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未售出'), (1, '已售出')], default=1, verbose_name='商品状态'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(default='group1/M00/00/00/wKj4gV4ls86AP8SuAAA6Lr96DVk744.jpg', upload_to='goods', verbose_name='图片路径'),
        ),
    ]
