# Generated by Django 2.2.5 on 2020-01-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20200121_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='fineness',
            field=models.SmallIntegerField(choices=[(2, '8成新'), (0, '全新'), (3, '7成新及以下'), (1, '9成新')], default=0, verbose_name='商品成色'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='update_time',
            field=models.DateTimeField(verbose_name='更新时间'),
        ),
    ]
