# Generated by Django 2.2.5 on 2020-01-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20200121_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='fineness',
            field=models.SmallIntegerField(choices=[(2, '8成新'), (1, '9成新'), (3, '7成新及以下'), (0, '全新')], default=0, verbose_name='商品成色'),
        ),
        migrations.AlterField(
            model_name='goodsleavemessage',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未回复'), (1, '已回复')], default=0, verbose_name='留言状态'),
        ),
    ]
