# Generated by Django 2.2.5 on 2020-01-21 10:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_auto_20200121_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='商品详情'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='fineness',
            field=models.SmallIntegerField(choices=[(3, '7成新及以下'), (2, '8成新'), (1, '9成新'), (0, '全新')], default=0, verbose_name='商品成色'),
        ),
    ]
