# Generated by Django 2.2.5 on 2020-01-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_auto_20200124_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(default='group1/M00/00/00/rB4AC14zm-mAIjmGAAA6Lr96DVk593.jpg', upload_to='goods', verbose_name='图片路径'),
        ),
    ]
