# Generated by Django 2.2.5 on 2020-01-31 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_auto_20200131_1122'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goodsleavemessage',
            table='st_goods_message',
        ),
    ]
