# Generated by Django 2.2.5 on 2020-01-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='comment_status',
            field=models.SmallIntegerField(choices=[(0, '差评'), (1, '好评')], default=1, verbose_name='评价'),
        ),
    ]
